### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by ewensam** [Fight-Club/fightclub#19]
If you google how to get the twitter link it comes up with the html for a 'follow @_TheFightClub' link. I assume Facebook wouldn't be much different if we wanted to post links on there.

**Comment by theref** [comment]
Awesome, where do you think it should be placed?

**Comment by ewensam** [comment]
I was thinking the about page for the follow link possibly on the top right?

**Comment by theref** [comment]
Ok then, I'll be making a contact page soon as well and put it on there too

**Comment by ewensam** [comment]
The 'mention' link could go there. 'For any queries, tweet @_TheFightClub' or something.

**Comment by theref** [comment]
yeah, that would work really well, i'll set contact page as a 'milestone' for the end of the week

**Comment by theref** [comment]
That's done now
