### ISSUE TITLE
could the code be commented please

### ISSUE THREAD

**Issue by mattj2294** [Fight-Club/fightclub#21]

**Comment by theref** [comment]
do you actually want it commented, or would some notes specific to the bits you're gonna talk about be more helpful?

**Comment by mattj2294** [comment]
Probably notes actually, I'll choose some things to talk about in the next couple of days and then request some information on those topics, thanks

**Comment by theref** [comment]
ok then, that saves me a lot of work!!

**Comment by mattj2294** [comment]
Good good :)
